import {
  BookOpen, BookmarkX, CheckCircle2, ChevronDown, ChevronRight, CircleDot, ExternalLink, Film, Filter, Globe2,
  History, Landmark, Library, PlayCircle, Search, ShieldAlert, ShieldCheck, Telescope, Trash2
} from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import type { DispensationRecord, ProphecyRecord } from '../../../shared/types'
import { ProphecyDrawer } from '../components/EntityDrawers'
import { BookmarkButton, ConfidenceBadge, EmptyState, Panel, ProphecyBadge } from '../components/ui'
import { useApp } from '../context/AppContext'

export const PropheciesPage = (): React.JSX.Element => {
  const { prophecies } = useApp()
  const [selected, setSelected] = useState<ProphecyRecord | null>(null)
  const [classification, setClassification] = useState('All')
  const classifications = ['All', ...new Set(prophecies.map((record) => record.classification))]
  const filtered = classification === 'All' ? prophecies : prophecies.filter((record) => record.classification === classification)
  return <div className="page prophecy-page"><header className="page-header"><div><span className="eyebrow">Evidence chains, not unsupported certainty</span><h1>Verified Prophecies</h1><p>Prophecy, historical events, supporting sources, and interpretive classifications remain separate and inspectable.</p></div><div className="classification-rule"><ShieldCheck /><span><strong>No silent fulfillment claims</strong><small>Every connection carries a visible classification.</small></span></div></header><Panel className="prophecy-filter"><Filter /><span>Classification</span>{classifications.map((value) => <button key={value} className={classification === value ? 'active' : ''} onClick={() => setClassification(value)}>{value}</button>)}</Panel><div className="prophecy-grid">{filtered.map((record) => <article key={record.id} className="prophecy-card" onClick={() => setSelected(record)}><header><span>{record.spokenDate}</span><BookmarkButton compact input={{ entityType: 'prophecy', entityId: record.id, title: record.title, subtitle: `${record.reference} · ${record.classification}` }} /></header><h2>{record.title}</h2><strong>{record.reference}</strong><p>{record.context}</p><div className="prophecy-arrow"><span>PROPHECY</span><ChevronRight /><span>PROPOSED FULFILLMENT</span></div><p className="fulfillment-text">{record.proposedFulfillment}</p><footer><ProphecyBadge value={record.classification} /><ConfidenceBadge value={record.confidence} /></footer></article>)}</div>{selected && <ProphecyDrawer prophecy={selected} onClose={() => setSelected(null)} />}</div>
}

export const DispensationsPage = (): React.JSX.Element => {
  const { dispensations } = useApp()
  const [openId, setOpenId] = useState(dispensations.find((record) => record.status === 'current')?.id || dispensations[0]?.id)
  return <div className="page dispensations-page"><header className="page-header"><div><span className="eyebrow">Chosen theological framework</span><h1>Dispensations</h1><p>TruthNewsApp initially uses a classic premillennial dispensational framework. Christians disagree on these divisions; the interface identifies interpretation rather than presenting it as universal consensus.</p></div><div className="framework-warning"><ShieldAlert /><span><strong>Theological framework</strong><small>Not every Christian tradition uses identical divisions.</small></span></div></header><div className="dispensation-sequence">{dispensations.map((record, index) => <button key={record.id} className={`${record.status} ${openId === record.id ? 'active' : ''}`} onClick={() => setOpenId(record.id)}><span>{index + 1}</span><strong>{record.name}</strong><small>{record.beginning}</small></button>)}</div><div className="dispensation-accordion">{dispensations.map((record) => <DispensationSection key={record.id} record={record} open={openId === record.id} onToggle={() => setOpenId(openId === record.id ? '' : record.id)} />)}</div></div>
}

const DispensationSection = ({ record, open, onToggle }: { record: DispensationRecord; open: boolean; onToggle: () => void }): React.JSX.Element => <article className={`dispensation-section ${open ? 'open' : ''}`}><button onClick={onToggle}><div><span className={`status-dot ${record.status}`} /><span><strong>{record.name}</strong><small>{record.beginning} → {record.end}</small></span></div><ChevronDown /></button>{open && <div className="dispensation-details"><section><span>Governing principle</span><p>{record.governingPrinciple}</p></section><section><span>Human responsibility</span><p>{record.responsibility}</p></section><section><span>Major figures</span><p>{record.figures.join(' · ')}</p></section><section><span>Covenants</span><p>{record.covenants.length ? record.covenants.join(' · ') : 'No named covenant assigned in this framework.'}</p></section><section><span>Major events</span><p>{record.events.join(' · ')}</p></section><section><span>Relevant Scripture</span><p>{record.scripture.join(' · ')}</p></section><section><span>Judgment or transition</span><p>{record.transition}</p></section><section className="wide"><span>Prophetic significance</span><p>{record.significance}</p></section></div>}</article>

export const SourcesPage = (): React.JSX.Element => {
  const { sources, updateSource } = useApp()
  const [category, setCategory] = useState('All')
  const [query, setQuery] = useState('')
  const categories = ['All', ...new Set(sources.map((source) => source.category))]
  const filtered = sources.filter((source) => (category === 'All' || source.category === category) && (!query || `${source.name} ${source.description}`.toLowerCase().includes(query.toLowerCase())))
  return <div className="page sources-page"><header className="page-header"><div><span className="eyebrow">Where did this claim come from?</span><h1>Sources</h1><p>Inspect publishers, biblical texts, historical references, government documents, feed status, terms notes, and retrieval history.</p></div><div className="source-count"><Library /><span><strong>{sources.length} registered sources</strong><small>{sources.filter((source) => source.enabled).length} enabled</small></span></div></header><Panel className="source-controls"><div className="inline-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a source…" /></div>{categories.map((value) => <button className={category === value ? 'active' : ''} onClick={() => setCategory(value)} key={value}>{value}</button>)}</Panel><div className="source-grid">{filtered.map((source) => <article className="source-card" key={source.id}><header><div className={`source-icon ${source.category}`}>{source.category === 'news' ? <Globe2 /> : source.category === 'biblical' ? <BookOpen /> : source.category === 'government' ? <Landmark /> : <History />}</div><div><span>{source.category}</span><h2>{source.name}</h2></div>{source.category === 'news' && <label className="switch"><input type="checkbox" checked={source.enabled} onChange={(event) => void updateSource(source.id, event.target.checked)} /><i /></label>}</header><p>{source.description}</p><dl><div><dt>Reliability note</dt><dd>{source.reliability}</dd></div><div><dt>Terms / rights</dt><dd>{source.termsNote}</dd></div>{source.lastSuccess && <div><dt>Last feed success</dt><dd>{new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(source.lastSuccess))}</dd></div>}{source.lastError && <div><dt>Last feed error</dt><dd className="source-error">{source.lastError}</dd></div>}</dl><footer><button className="gold-button" onClick={() => void window.truthNews.openExternal(source.url)}>Open source <ExternalLink size={15} /></button><BookmarkButton compact input={{ entityType: 'source', entityId: source.id, title: source.name, subtitle: `${source.category} · ${source.url}` }} /></footer></article>)}</div></div>
}

export const BookmarksPage = (): React.JSX.Element => {
  const { bookmarks, toggleBookmark } = useApp()
  const navigate = useNavigate()
  const routeFor = (type: string): string => type === 'news' ? '/news' : type === 'event' ? '/timeline/master' : type === 'prophecy' ? '/prophecies' : type === 'verse' ? '/bible' : '/sources'
  return <div className="page bookmarks-page"><header className="page-header"><div><span className="eyebrow">Device-local research collection</span><h1>Bookmarks</h1><p>Saved articles, events, prophecies, verses, and sources remain on this PC. No account or cloud service is required.</p></div></header>{bookmarks.length ? <div className="bookmark-list">{bookmarks.map((bookmark) => <article key={bookmark.id}><button className="bookmark-main" onClick={() => navigate(routeFor(bookmark.entityType))}><i>{bookmark.entityType === 'verse' ? <BookOpen /> : bookmark.entityType === 'news' ? <Globe2 /> : bookmark.entityType === 'event' ? <History /> : bookmark.entityType === 'prophecy' ? <Telescope /> : <Library />}</i><span><small>{bookmark.folder} · {bookmark.entityType}</small><strong>{bookmark.title}</strong><p>{bookmark.subtitle}</p><em>Saved {new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(bookmark.createdAt))}</em></span><ChevronRight /></button><button className="remove-bookmark" onClick={() => void toggleBookmark({ entityType: bookmark.entityType, entityId: bookmark.entityId, title: bookmark.title, subtitle: bookmark.subtitle })} aria-label="Remove bookmark"><BookmarkX /></button></article>)}</div> : <EmptyState title="No bookmarks yet" detail="Use the bookmark control on news, events, prophecies, Bible verses, or source records to build a local research collection." />}</div>
}

const MEDIA_RESOURCES = [
  { title: 'BibleProject Classroom & Guides', provider: 'BibleProject', type: 'Bible teaching', detail: 'Animated overviews and structured biblical-literacy resources. Opens the provider website.', url: 'https://bibleproject.com/explore/', icon: BookOpen },
  { title: 'The British Museum Collection', provider: 'The British Museum', type: 'Archaeology', detail: 'Explore catalogued objects from the ancient Near East and wider world.', url: 'https://www.britishmuseum.org/collection', icon: Landmark },
  { title: 'Library of Congress — Religion', provider: 'Library of Congress', type: 'Primary sources', detail: 'Search digitized historical material and institutional collections.', url: 'https://www.loc.gov/religion/', icon: Library },
  { title: 'BibleProject Video Library', provider: 'BibleProject', type: 'Watch', detail: 'Official video collection. Media is not embedded or copied into TruthNewsApp.', url: 'https://bibleproject.com/videos/', icon: Film }
]

const WATCH_TOPICS = ['Israel', 'Jerusalem', 'Middle East wars', 'Global governance', 'Religious persecution', 'Wars', 'Famines', 'Earthquakes']

export const WatchPage = (): React.JSX.Element => {
  const [topics, setTopics] = useState<string[]>(['Israel', 'Jerusalem', 'Religious persecution'])
  const toggle = (topic: string): void => setTopics((current) => current.includes(topic) ? current.filter((item) => item !== topic) : [...current, topic])
  return <div className="page watch-page"><header className="page-header"><div><span className="eyebrow">Study media and cautious topic monitoring</span><h1>Watch & Learn</h1><p>Open authorized external teaching, historical, and archaeological resources. TruthNewsApp does not copy or embed copyrighted media without permission.</p></div></header><Panel title="Prophecy Watch topics" className="watch-topics" action={<span>{topics.length} active</span>}><p>These topics organize relevant current events. Matching a topic means <strong>potential relevance</strong> only—not fulfillment.</p><div>{WATCH_TOPICS.map((topic) => <button key={topic} className={topics.includes(topic) ? 'active' : ''} onClick={() => toggle(topic)}>{topics.includes(topic) ? <CheckCircle2 /> : <CircleDot />}{topic}</button>)}</div></Panel><div className="media-grid">{MEDIA_RESOURCES.map(({ title, provider, type, detail, url, icon: Icon }) => <article key={title}><div className="media-art"><Icon /></div><span>{type}</span><h2>{title}</h2><p>{detail}</p><footer><small>{provider}</small><button className="gold-button" onClick={() => void window.truthNews.openExternal(url)}><PlayCircle />Open resource</button></footer></article>)}</div><Panel title="Potential Prophetic Relevance" className="relevance-panel"><Telescope /><div><strong>Review required</strong><p>When synchronized news matches one of the active topics, the application may surface it for study. A reviewer must still attach relevant Scripture, historical context, an interpretation, and one of the defined confidence classifications.</p></div></Panel></div>
}
