import type { AppSettings, DispensationRecord, ProphecyRecord, SourceRecord, TimelineEvent } from '../shared/types'

export const DEFAULT_SETTINGS: AppSettings = {
  theme: 'dark-gold',
  refreshMinutes: 30,
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'America/Toronto',
  country: 'Canada',
  language: 'English',
  defaultBible: 'WEB',
  dateFormat: 'long',
  reducedMotion: false,
  sidebarCollapsed: false
}

export const SEED_EVENTS: TimelineEvent[] = [
  {
    id: 'event-creation',
    title: 'Creation',
    summary: 'The biblical beginning of the heavens and the earth. Scripture does not supply a universally agreed modern calendar date, and proposed chronologies vary.',
    category: 'Bible',
    region: 'Global',
    date: { dateType: 'disputed', era: 'BC', displayDate: 'Date disputed — traditional chronologies vary', confidence: 'DISPUTED' },
    scripture: 'Genesis 1–2',
    sourceIds: ['source-web'],
    relationshipIds: ['event-fall'],
    tags: ['creation', 'genesis', 'origins']
  },
  {
    id: 'event-fall',
    title: 'The Fall',
    summary: 'The Genesis account of humanity’s disobedience and separation from God. No exact historical calendar date is asserted.',
    category: 'Bible',
    region: 'Ancient Near East',
    date: { dateType: 'unknown', era: 'BC', displayDate: 'Date Unknown', confidence: 'UNKNOWN' },
    scripture: 'Genesis 3',
    sourceIds: ['source-web'],
    relationshipIds: ['event-creation'],
    tags: ['adam', 'eve', 'sin', 'genesis']
  },
  {
    id: 'event-abraham',
    title: 'Abrahamic Covenant',
    summary: 'God’s covenant promises to Abraham concerning descendants, land, and blessing to the nations. The calendar placement is an approximate traditional chronology.',
    category: 'Bible',
    region: 'Canaan',
    date: { dateType: 'approximate', era: 'BC', startYear: 2000, displayDate: 'c. 2000 BC', confidence: 'APPROXIMATE' },
    scripture: 'Genesis 12:1–3; 15; 17',
    sourceIds: ['source-web'],
    relationshipIds: ['event-david', 'event-birth-jesus'],
    latitude: 31.7683,
    longitude: 35.2137,
    tags: ['abraham', 'covenant', 'promise', 'israel']
  },
  {
    id: 'event-david',
    title: 'Davidic Kingdom',
    summary: 'The reign of David and the covenant promise concerning his royal house. Exact regnal dates vary slightly among chronologies.',
    category: 'Bible',
    region: 'Israel',
    date: { dateType: 'approximate', era: 'BC', startYear: 1000, displayDate: 'c. 1000 BC', confidence: 'APPROXIMATE' },
    scripture: '2 Samuel 5–7',
    sourceIds: ['source-web'],
    relationshipIds: ['event-abraham', 'event-birth-jesus'],
    latitude: 31.7683,
    longitude: 35.2137,
    tags: ['david', 'kingdom', 'jerusalem', 'messiah']
  },
  {
    id: 'event-jerusalem-fall',
    title: 'Babylonian Destruction of Jerusalem',
    summary: 'Babylon captured Jerusalem, destroyed the First Temple, and carried many Judeans into exile. The year is commonly placed in 587 or 586 BC.',
    category: 'World History',
    region: 'Judah',
    date: { dateType: 'disputed', era: 'BC', startYear: 586, endYear: 587, displayDate: '587/586 BC', confidence: 'HIGH CONFIDENCE' },
    scripture: '2 Kings 25; Jeremiah 39',
    sourceIds: ['source-web', 'source-britannica-exile'],
    relationshipIds: ['event-cyrus-decree', 'event-jerusalem-70'],
    latitude: 31.7683,
    longitude: 35.2137,
    tags: ['babylon', 'exile', 'jerusalem', 'temple']
  },
  {
    id: 'event-cyrus-decree',
    title: 'Cyrus Permits the Return',
    summary: 'After Persia conquered Babylon, Cyrus permitted displaced peoples to return and restore sanctuaries. Ezra connects this policy to the return to Jerusalem.',
    category: 'World History',
    region: 'Persian Empire',
    date: { dateType: 'approximate', era: 'BC', startYear: 538, displayDate: 'c. 538 BC', confidence: 'HIGH CONFIDENCE' },
    scripture: 'Ezra 1:1–4; Isaiah 44:28–45:1',
    sourceIds: ['source-web', 'source-british-museum-cyrus'],
    relationshipIds: ['event-jerusalem-fall'],
    tags: ['cyrus', 'persia', 'return', 'temple']
  },
  {
    id: 'event-birth-jesus',
    title: 'Birth of Jesus Christ',
    summary: 'The Gospels place Jesus’ birth in Bethlehem during the reign of Herod the Great. Proposed calendar years commonly fall between 6 and 4 BC.',
    category: 'Jesus Christ',
    region: 'Judea',
    date: { dateType: 'range', era: 'BC', startYear: 6, endYear: 4, displayDate: 'c. 6–4 BC', confidence: 'APPROXIMATE' },
    scripture: 'Matthew 1–2; Luke 1–2',
    sourceIds: ['source-web'],
    relationshipIds: ['event-abraham', 'event-david', 'event-ministry-jesus'],
    latitude: 31.7054,
    longitude: 35.2024,
    tags: ['jesus', 'bethlehem', 'nativity', 'messiah']
  },
  {
    id: 'event-ministry-jesus',
    title: 'Public Ministry of Jesus',
    summary: 'Jesus taught, called disciples, proclaimed God’s Kingdom, and performed signs recorded by the Gospels. Reconstructed chronologies vary.',
    category: 'Jesus Christ',
    region: 'Galilee and Judea',
    date: { dateType: 'range', era: 'AD', startYear: 27, endYear: 30, displayDate: 'c. AD 27–30', confidence: 'APPROXIMATE' },
    scripture: 'Matthew; Mark; Luke; John',
    sourceIds: ['source-web'],
    relationshipIds: ['event-birth-jesus', 'event-crucifixion'],
    latitude: 32.794,
    longitude: 35.531,
    tags: ['jesus', 'ministry', 'gospel', 'galilee']
  },
  {
    id: 'event-crucifixion',
    title: 'Crucifixion of Jesus',
    summary: 'Jesus was crucified in Jerusalem under Pontius Pilate. AD 30 and AD 33 are leading proposed dates; the application preserves the disagreement.',
    category: 'Jesus Christ',
    region: 'Jerusalem',
    date: { dateType: 'disputed', era: 'AD', startYear: 30, endYear: 33, displayDate: 'AD 30 or 33 — Date Disputed', confidence: 'DISPUTED' },
    scripture: 'Matthew 27; Mark 15; Luke 23; John 19',
    sourceIds: ['source-web'],
    relationshipIds: ['event-ministry-jesus', 'event-resurrection'],
    latitude: 31.7785,
    longitude: 35.2296,
    tags: ['jesus', 'cross', 'pilate', 'jerusalem']
  },
  {
    id: 'event-resurrection',
    title: 'Resurrection of Jesus',
    summary: 'The New Testament testimony that Jesus rose bodily from the dead on the third day—the central historical claim of the Christian faith.',
    category: 'Jesus Christ',
    region: 'Jerusalem',
    date: { dateType: 'disputed', era: 'AD', startYear: 30, endYear: 33, displayDate: 'AD 30 or 33 — tied to disputed crucifixion chronology', confidence: 'DISPUTED' },
    scripture: 'Matthew 28; Mark 16; Luke 24; John 20; 1 Corinthians 15:3–8',
    sourceIds: ['source-web'],
    relationshipIds: ['event-crucifixion', 'event-pentecost'],
    latitude: 31.7785,
    longitude: 35.2296,
    tags: ['jesus', 'resurrection', 'gospel', 'christianity']
  },
  {
    id: 'event-pentecost',
    title: 'Pentecost and the Apostolic Church',
    summary: 'Acts records the outpouring of the Holy Spirit and the public witness of the apostles in Jerusalem.',
    category: 'Church History',
    region: 'Jerusalem',
    date: { dateType: 'approximate', era: 'AD', startYear: 30, endYear: 33, displayDate: 'c. AD 30–33', confidence: 'APPROXIMATE' },
    scripture: 'Acts 2',
    sourceIds: ['source-web'],
    relationshipIds: ['event-resurrection', 'event-reformation'],
    tags: ['pentecost', 'church', 'apostles', 'holy spirit']
  },
  {
    id: 'event-jerusalem-70',
    title: 'Roman Destruction of Jerusalem',
    summary: 'Roman forces under Titus captured Jerusalem and destroyed the Second Temple during the First Jewish–Roman War.',
    category: 'World History',
    region: 'Judea',
    date: { dateType: 'exact', era: 'AD', startYear: 70, displayDate: 'AD 70', confidence: 'CERTAIN' },
    scripture: 'Compare Luke 19:41–44; 21:5–24',
    sourceIds: ['source-britannica-jerusalem'],
    relationshipIds: ['event-jerusalem-fall'],
    latitude: 31.7683,
    longitude: 35.2137,
    tags: ['rome', 'titus', 'jerusalem', 'temple']
  },
  {
    id: 'event-reformation',
    title: 'Beginning of the Protestant Reformation',
    summary: 'Martin Luther’s Ninety-five Theses became a catalytic event in the sixteenth-century Reformation.',
    category: 'Church History',
    region: 'Europe',
    date: { dateType: 'exact', era: 'AD', startYear: 1517, month: 10, day: 31, displayDate: 'October 31, 1517', confidence: 'HIGH CONFIDENCE' },
    sourceIds: ['source-britannica-reformation'],
    relationshipIds: ['event-pentecost'],
    latitude: 51.8661,
    longitude: 12.6464,
    tags: ['reformation', 'luther', 'church history', 'europe']
  },
  {
    id: 'event-israel-1948',
    title: 'Declaration of the State of Israel',
    summary: 'Jewish leaders proclaimed the establishment of the State of Israel in Tel Aviv. The historical event is certain; prophetic interpretations are evaluated separately.',
    category: 'Israel',
    region: 'Israel',
    date: { dateType: 'exact', era: 'AD', startYear: 1948, month: 5, day: 14, displayDate: 'May 14, 1948', confidence: 'CERTAIN' },
    sourceIds: ['source-israel-declaration'],
    relationshipIds: [],
    latitude: 32.0853,
    longitude: 34.7818,
    tags: ['israel', 'statehood', 'middle east', 'jewish history']
  }
]

export const SEED_PROPHECIES: ProphecyRecord[] = [
  {
    id: 'prophecy-micah-bethlehem',
    title: 'Ruler from Bethlehem',
    speaker: 'Micah',
    reference: 'Micah 5:2',
    originalAudience: 'Judah',
    historicalSetting: 'Judah under Assyrian pressure in the eighth century BC',
    spokenDate: 'c. eighth century BC',
    context: 'A promised ruler is associated with Bethlehem Ephrathah.',
    proposedFulfillment: 'Birth of Jesus in Bethlehem as presented by Matthew and Luke',
    fulfillmentDate: 'c. 6–4 BC',
    evidence: ['Micah 5:2', 'Matthew 2:1–6', 'Luke 2:1–7'],
    relatedScripture: ['Matthew 2:1–6', 'Luke 2:1–7'],
    interpretation: 'The New Testament explicitly applies the Bethlehem expectation to Jesus.',
    currentRelevance: 'A foundational Christian messianic claim.',
    classification: 'EXPLICITLY FULFILLED',
    confidence: 'HIGH CONFIDENCE',
    relatedEventIds: ['event-birth-jesus']
  },
  {
    id: 'prophecy-zechariah-king',
    title: 'The King Comes Humbly',
    speaker: 'Zechariah',
    reference: 'Zechariah 9:9',
    originalAudience: 'Post-exilic Judah',
    historicalSetting: 'The Persian period after the return from exile',
    spokenDate: 'Date disputed within the Persian period',
    context: 'Zion is called to rejoice as her king comes humble and riding on a donkey.',
    proposedFulfillment: 'Jesus’ entry into Jerusalem',
    fulfillmentDate: 'c. AD 30 or 33',
    evidence: ['Zechariah 9:9', 'Matthew 21:1–11', 'John 12:12–16'],
    relatedScripture: ['Matthew 21:1–11', 'John 12:12–16'],
    interpretation: 'The Gospel writers explicitly connect the entry to Zechariah’s words.',
    currentRelevance: 'Supports the Christian understanding of Jesus as the promised King.',
    classification: 'EXPLICITLY FULFILLED',
    confidence: 'HIGH CONFIDENCE',
    relatedEventIds: ['event-ministry-jesus', 'event-crucifixion']
  },
  {
    id: 'prophecy-isaiah-servant',
    title: 'The Suffering Servant',
    speaker: 'Isaiah',
    reference: 'Isaiah 52:13–53:12',
    originalAudience: 'Judah and the exilic community',
    historicalSetting: 'Isaianic prophetic literature; authorship and dating questions are debated in scholarship',
    spokenDate: 'Date disputed',
    context: 'The servant suffers, bears sin, is rejected, and is ultimately vindicated.',
    proposedFulfillment: 'The suffering, death, and resurrection of Jesus',
    fulfillmentDate: 'c. AD 30 or 33',
    evidence: ['Isaiah 52:13–53:12', 'Acts 8:26–35', '1 Peter 2:21–25'],
    relatedScripture: ['Luke 22:37', 'Acts 8:26–35', '1 Peter 2:21–25'],
    interpretation: 'Christian tradition and New Testament writers associate the servant passage with Jesus; Jewish and academic interpretations differ.',
    currentRelevance: 'Central to Christian teaching about substitutionary suffering and redemption.',
    classification: 'HISTORICALLY ASSOCIATED',
    confidence: 'HIGH CONFIDENCE',
    relatedEventIds: ['event-crucifixion', 'event-resurrection']
  },
  {
    id: 'prophecy-jerusalem-destruction',
    title: 'Jerusalem and the Temple Foretold',
    speaker: 'Jesus Christ',
    reference: 'Luke 19:41–44; 21:5–24',
    originalAudience: 'Jesus’ disciples and Jerusalem',
    historicalSetting: 'Roman Judea before the First Jewish–Roman War',
    spokenDate: 'c. AD 30 — chronology disputed',
    context: 'Jesus warns of siege, devastation, and the Temple’s destruction.',
    proposedFulfillment: 'Roman siege and destruction of Jerusalem in AD 70',
    fulfillmentDate: 'AD 70',
    evidence: ['Luke 19:41–44', 'Luke 21:5–24', 'Josephus, Jewish War', 'Roman historical context'],
    relatedScripture: ['Matthew 24:1–2', 'Mark 13:1–2'],
    interpretation: 'Many Christian interpreters associate at least part of the discourse with AD 70; the extent of fulfillment remains disputed.',
    currentRelevance: 'Important for interpreting the Olivet discourse and distinguishing past judgment from future expectation.',
    classification: 'HISTORICALLY ASSOCIATED',
    confidence: 'PROBABLE',
    relatedEventIds: ['event-jerusalem-70']
  },
  {
    id: 'prophecy-israel-restoration',
    title: 'Israel’s National Restoration',
    speaker: 'Ezekiel',
    reference: 'Ezekiel 36–37',
    originalAudience: 'Judean exiles',
    historicalSetting: 'Babylonian exile',
    spokenDate: 'sixth century BC',
    context: 'Restoration imagery includes return to the land, national renewal, and spiritual transformation.',
    proposedFulfillment: 'Return from Babylon; some interpreters also connect modern Israel or a future spiritual restoration',
    fulfillmentDate: 'Multiple proposed fulfillments',
    evidence: ['Ezekiel 36–37', 'Ezra 1–6', 'State of Israel declaration, 1948'],
    relatedScripture: ['Romans 11:25–29'],
    interpretation: 'The immediate exilic context is clear; connections to the modern State of Israel and future events differ among Christian traditions.',
    currentRelevance: 'Frequently discussed in modern prophecy study and therefore requires careful classification.',
    classification: 'DISPUTED',
    confidence: 'DISPUTED',
    relatedEventIds: ['event-cyrus-decree', 'event-israel-1948']
  },
  {
    id: 'prophecy-new-creation',
    title: 'The New Heaven and New Earth',
    speaker: 'John’s Revelation',
    reference: 'Revelation 21–22',
    originalAudience: 'The seven churches of Asia and the wider Church',
    historicalSetting: 'Early Christianity under Roman imperial power; exact date is debated',
    spokenDate: 'first century AD — Date Disputed',
    context: 'God dwells with His people, abolishes death and sorrow, and makes all things new.',
    proposedFulfillment: 'Future consummation of God’s redemptive plan',
    fulfillmentDate: 'Future — date unknown',
    evidence: ['Revelation 21–22'],
    relatedScripture: ['Isaiah 65:17', '2 Peter 3:13'],
    interpretation: 'The application’s premillennial framework treats the final new creation as future.',
    currentRelevance: 'Grounds Christian hope while providing no basis for date-setting.',
    classification: 'FUTURE',
    confidence: 'HIGH CONFIDENCE',
    relatedEventIds: []
  }
]

export const SEED_DISPENSATIONS: DispensationRecord[] = [
  { id: 'disp-innocence', name: 'Innocence', beginning: 'Creation', end: 'The Fall — Date Unknown', governingPrinciple: 'Direct fellowship and one explicit prohibition', responsibility: 'Obey God concerning the tree of the knowledge of good and evil', figures: ['Adam', 'Eve'], covenants: [], events: ['Creation', 'The Fall'], scripture: ['Genesis 1:26–3:24'], transition: 'Judgment and expulsion from Eden', significance: 'Introduces humanity’s created purpose and fall into sin.', status: 'past' },
  { id: 'disp-conscience', name: 'Conscience', beginning: 'The Fall', end: 'The Flood — chronology disputed', governingPrinciple: 'Moral accountability informed by conscience', responsibility: 'Do good and approach God in faith', figures: ['Adam', 'Cain', 'Abel', 'Seth', 'Noah'], covenants: [], events: ['Cain and Abel', 'Growth of violence', 'The Flood'], scripture: ['Genesis 3:22–8:22'], transition: 'Worldwide judgment in the Flood', significance: 'Shows the inability of conscience alone to restrain human evil.', status: 'past' },
  { id: 'disp-government', name: 'Human Government', beginning: 'After the Flood', end: 'Call of Abraham — approximate', governingPrinciple: 'Delegated human authority and civil order', responsibility: 'Govern justly, preserve life, and multiply', figures: ['Noah', 'Noah’s descendants', 'Nimrod'], covenants: ['Noahic Covenant'], events: ['Noahic covenant', 'Tower of Babel', 'Division of nations'], scripture: ['Genesis 8:20–11:32'], transition: 'Scattering at Babel and the call of Abraham', significance: 'Establishes nations and delegated responsibility.', status: 'past' },
  { id: 'disp-promise', name: 'Promise', beginning: 'Call of Abraham — c. 2000 BC', end: 'Giving of the Law — chronology disputed', governingPrinciple: 'God’s covenant promises to Abraham and his descendants', responsibility: 'Live by faith in God’s promises', figures: ['Abraham', 'Isaac', 'Jacob', 'Joseph'], covenants: ['Abrahamic Covenant'], events: ['Patriarchs', 'Israel in Egypt', 'Exodus'], scripture: ['Genesis 12:1–Exodus 19:2'], transition: 'Israel receives the Mosaic Law at Sinai', significance: 'Establishes the covenant line through which blessing comes to the nations.', status: 'past' },
  { id: 'disp-law', name: 'Law', beginning: 'Sinai — chronology disputed', end: 'Cross and Pentecost — c. AD 30–33', governingPrinciple: 'The Mosaic covenant and its commandments', responsibility: 'Covenant faithfulness under the Law', figures: ['Moses', 'Joshua', 'Judges', 'David', 'Prophets', 'Jesus Christ'], covenants: ['Mosaic Covenant', 'Davidic Covenant'], events: ['Conquest', 'Kingdom', 'Exile', 'Return', 'Ministry of Jesus'], scripture: ['Exodus 19–John 19'], transition: 'Death and resurrection of Christ and the coming of the Holy Spirit', significance: 'Reveals God’s holiness, human sin, and the need for the promised Messiah.', status: 'past' },
  { id: 'disp-grace', name: 'Grace / Church Age', beginning: 'Pentecost — c. AD 30–33', end: 'Future — timing disputed', governingPrinciple: 'The gospel of grace and the indwelling Holy Spirit', responsibility: 'Trust in Jesus Christ and bear witness to the gospel', figures: ['Jesus Christ', 'Apostles', 'The Church'], covenants: ['New Covenant'], events: ['Pentecost', 'Great Commission', 'Global spread of Christianity'], scripture: ['Acts 2; Romans 3:21–26; Ephesians 2:8–10'], transition: 'Future events vary by eschatological framework', significance: 'The application identifies the present era as the Church Age within its chosen dispensational framework.', status: 'current' },
  { id: 'disp-tribulation', name: 'Tribulation', beginning: 'Future — timing disputed', end: 'Second Coming of Christ', governingPrinciple: 'Divine judgment and intensified prophetic events', responsibility: 'Repent and remain faithful to God', figures: ['Future figures interpreted differently among Christians'], covenants: [], events: ['Events associated with Daniel and Revelation'], scripture: ['Daniel 9:24–27; Matthew 24; Revelation 6–19'], transition: 'Second Coming of Jesus Christ', significance: 'Future within this premillennial dispensational framework; details remain debated.', status: 'future' },
  { id: 'disp-millennium', name: 'Millennial Kingdom', beginning: 'Second Coming of Christ', end: 'Final judgment and new creation', governingPrinciple: 'The righteous reign of Jesus Christ', responsibility: 'Submit to the King', figures: ['Jesus Christ', 'Resurrected saints'], covenants: [], events: ['Messianic reign', 'Final rebellion', 'Final judgment'], scripture: ['Revelation 19:11–20:15'], transition: 'New heaven and new earth', significance: 'Future earthly reign as understood by the application’s premillennial framework.', status: 'future' }
]

export const SEED_SOURCES: SourceRecord[] = [
  {
    id: 'source-web',
    name: 'World English Bible',
    category: 'biblical',
    url: 'https://ebible.org/details.php?id=engwebp',
    description: 'Complete public-domain modern-English Bible text used by the offline reader.',
    reliability: 'Primary biblical text; translation decisions should be compared when interpretation depends on wording.',
    enabled: true,
    termsNote: 'Public domain. “World English Bible” is a trademark of eBible.org; the text is stored without alteration.'
  },
  {
    id: 'source-christian-post',
    name: 'The Christian Post',
    category: 'news',
    url: 'https://www.christianpost.com/',
    feedUrl: 'https://www.christianpost.com/rss',
    description: 'Christian news and commentary. Factual reporting and opinion labels remain distinct in TruthNewsApp.',
    reliability: 'Publisher feed; verify consequential claims against primary documentation and additional reporting.',
    enabled: true,
    termsNote: 'Publisher-provided RSS feed containing headlines, summaries, timestamps, and links.'
  },
  {
    id: 'source-christian-post-politics',
    name: 'The Christian Post — Politics',
    category: 'news',
    url: 'https://www.christianpost.com/category/politics',
    feedUrl: 'https://www.christianpost.com/category/politics/rss',
    description: 'Politics reporting and commentary from The Christian Post.',
    reliability: 'Publisher feed; commentary is labeled and should not be mistaken for objective reporting.',
    enabled: true,
    termsNote: 'Publisher-provided RSS feed.'
  },
  {
    id: 'source-jpost',
    name: 'The Jerusalem Post',
    category: 'news',
    url: 'https://www.jpost.com/',
    feedUrl: 'https://www.jpost.com/rss/rssfeedsfrontpage.aspx',
    description: 'Israel, Middle East, Jewish world, and international reporting.',
    reliability: 'Publisher feed; cross-check fast-moving conflict reporting and clearly separate opinion.',
    enabled: true,
    termsNote: 'Publisher terms expressly permit application use of content presented in its RSS feed with attribution.'
  },
  {
    id: 'source-jpost-israel',
    name: 'The Jerusalem Post — Israel News',
    category: 'news',
    url: 'https://www.jpost.com/israel-news',
    feedUrl: 'https://www.jpost.com/rss/rssfeedsisraelnews.aspx',
    description: 'Focused Israel news feed from The Jerusalem Post.',
    reliability: 'Publisher feed; cross-check breaking developments against primary and additional sources.',
    enabled: true,
    termsNote: 'Publisher-provided RSS feed with source attribution preserved.'
  },
  {
    id: 'source-fox-latest',
    name: 'Fox News — Latest',
    category: 'news',
    url: 'https://www.foxnews.com/',
    feedUrl: 'https://moxie.foxnews.com/google-publisher/latest.xml',
    description: 'Latest national and international headlines from Fox News.',
    reliability: 'Publisher feed; distinguish straight reporting from analysis and opinion.',
    enabled: true,
    termsNote: 'Publisher-operated XML syndication feed; display is limited to supplied metadata and links.'
  },
  {
    id: 'source-british-museum-cyrus',
    name: 'The British Museum — Cyrus Cylinder',
    category: 'historical',
    url: 'https://www.britishmuseum.org/collection/object/W_1880-0617-1941',
    description: 'Museum collection record for the Cyrus Cylinder, a primary ancient object with modern scholarly cataloguing.',
    reliability: 'Primary artifact and institutional catalogue.',
    enabled: true,
    termsNote: 'Linked reference only; no museum media is bundled.'
  },
  {
    id: 'source-israel-declaration',
    name: 'Israel Ministry of Foreign Affairs — Declaration',
    category: 'government',
    url: 'https://www.gov.il/en/pages/declaration-of-establishment-state-of-israel',
    description: 'Government-hosted text and context for Israel’s declaration of independence.',
    reliability: 'Primary government document for the declaration; interpretation requires broader historical sources.',
    enabled: true,
    termsNote: 'Linked primary source.'
  },
  {
    id: 'source-britannica-exile',
    name: 'Encyclopaedia Britannica — Babylonian Captivity',
    category: 'historical',
    url: 'https://www.britannica.com/event/Babylonian-Captivity',
    description: 'Secondary reference overview of the Babylonian captivity.',
    reliability: 'General scholarly reference; consult specialist and primary sources for detailed disputes.',
    enabled: true,
    termsNote: 'Linked reference only.'
  },
  {
    id: 'source-britannica-jerusalem',
    name: 'Encyclopaedia Britannica — Siege of Jerusalem',
    category: 'historical',
    url: 'https://www.britannica.com/event/Siege-of-Jerusalem-70',
    description: 'Secondary reference overview of the Roman siege and destruction in AD 70.',
    reliability: 'General scholarly reference; compare Josephus and modern specialist scholarship.',
    enabled: true,
    termsNote: 'Linked reference only.'
  },
  {
    id: 'source-britannica-reformation',
    name: 'Encyclopaedia Britannica — Reformation',
    category: 'historical',
    url: 'https://www.britannica.com/event/Reformation',
    description: 'Secondary reference overview of the Protestant Reformation.',
    reliability: 'General scholarly reference.',
    enabled: true,
    termsNote: 'Linked reference only.'
  }
]
